set(_CATKIN_CURRENT_PACKAGE "face_detection")
set(face_detection_MAINTAINER "group11 <group11@todo.todo>")
set(face_detection_DEPRECATED "")
set(face_detection_VERSION "0.0.0")
set(face_detection_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(face_detection_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(face_detection_BUILDTOOL_DEPENDS "catkin")